services:
  poc-app:
    container_name: poc-app
    build: app/
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8085:80
    volumes:
      - ./app:/app

  poc-iac:
    container_name: poc-iac
    build:
      context: .
      dockerfile: ./iac/Dockerfile
    entrypoint: tail -f /dev/null
    volumes:
      - ./iac:/app/iac
      - ./scripts:/app/scripts
      - ./tasks:/app/tasks
    env_file:
      - .env
      - ./conn/aws
